=== MiguelGuthridge/portfolio/data/projects/project.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Project",
  "description": "A project in my portfolio",
  "type": "object",
  "properties": {
    "name": {
      "description": "name of the project",
      "type": "string"
    },
    "description": {
      "description": "description of the project",
      "type": "string"
    },
    "status": {
      "description": "the status of the project's development",
      "type": "string",
      "enum": [
        "In-progress",
        "Active",
        "Complete",
        "Incomplete"
      ]
    },
    "languages": {
      "description": "Programming languages used by the project",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "frameworks": {
      "description": "Programming frameworks used by the project",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "skills": {
      "description": "Skills demonstrated by the project",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "repo": {
      "description": "The repository where the project source code can be found",
      "type": "string"
    },
    "site": {
      "description": "The URL of the website where the project is hosted",
      "type": "string"
    },
    "package": {
      "description": "The package from which the project can be installed",
      "type": "object",
      "properties": {
        "command": {
          "description": "The command to use when installing the package",
          "url": "The URL to find the project on the package management website"
        }
      }
    }
  },
  "required": [
    "name",
    "description",
    "status",
    "languages",
    "frameworks",
    "skills"
  ]
}

=== MiguelGuthridge/portfolio/data/projects/universal-controller-script/info.json
{
  "$schema": "../project.schema.json",
  "name": "Universal Controller Script",
  "description": "An advanced compatibility layer to provide best-in-class integration between numerous hardware MIDI controllers and FL Studio",
  "status": "Active",
  "repo": "https://github.com/MiguelGuthridge/Universal-Controller-Script",
  "languages": ["python"],
  "frameworks": ["fl-studio-midi-controller-scripting"],
  "skills": [
    "type-safety"
  ]
}

=== MiguelGuthridge/portfolio/data/projects/waydriver/info.json
{
  "$schema": "../project.schema.json",
  "name": "Waydriver",
  "description": "An advanced task management system",
  "status": "In-progress",
  "repo": "https://github.com/Waydriver",
  "languages": ["typescript"],
  "frameworks": [
    "express",
    "next"
  ],
  "skills": [
    "fullstack"
  ]
}

=== MiguelGuthridge/portfolio/data/projects/fl-studio-api-stubs/info.json
{
  "$schema": "../project.schema.json",
  "name": "FL Studio API Stubs",
  "description": "Type definitions, and full documentation for FL Studio's MIDI Controller Scripting API",
  "status": "Active",
  "repo": "https://github.com/MiguelGuthridge/FL-Studio-API-Stubs",
  "site": "https://miguelguthridge.github.io/FL-Studio-API-Stubs/",
  "languages": ["python"],
  "frameworks": [
    "fl-studio-midi-controller-scripting",
    "mkdocs"
  ],
  "skills": [],
  "package": {
    "url": "https://pypi.org/project/fl-studio-api-stubs/",
    "command": "pip install fl-studio-api-stubs"
  }
}

=== MiguelGuthridge/portfolio/data/projects/equator/info.json
{
  "name": "Equator",
  "description": "A symbolic math interpreter built using Sympy",
  "status": "Complete",
  "repo": "https://github.com/MiguelGuthridge/Equator",
  "languages": ["python"],
  "frameworks": [
    "sympy",
    "ncurses"
  ],
  "skills": [
    "static-analysis"
  ],
  "package": {
    "url": "https://pypi.org/project/equatorpy/",
    "command": "pip install equatorpy"
  }
}

=== MiguelGuthridge/portfolio/data/projects/jestspectation/info.json
{
  "$schema": "../project.schema.json",
  "name": "Jestspectation",
  "description": "A powerful pattern matching system inspired by the Jest framework",
  "status": "Active",
  "repo": "https://github.com/MiguelGuthridge/Jestspectation",
  "languages": ["python"],
  "frameworks": ["pytest"],
  "skills": [],
  "package": {
    "url": "https://pypi.org/project/jestspectation/",
    "command": "pip install jestspectation"
  }
}

=== MiguelGuthridge/portfolio/data/projects/portfolio/info.json
{
  "$schema": "../project.schema.json",
  "name": "Portfolio",
  "description": "My portfolio website -- you're looking at it",
  "status": "Active",
  "repo": "https://github.com/MiguelGuthridge/miguelguthridge.com",
  "site": "https://miguelguthridge.com",
  "languages": ["typescript"],
  "frameworks": ["next"],
  "skills": []
}
